routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'BookController@index');

Route::get('/books', 'BookController@index');
Route::get('/books/create', 'BookController@create');
Route::post('/books', 'BookController@store');
Route::get('/books/{book}', 'BookController@show');
Route::get('/books/{book}/edit', 'BookController@edit');
Route::put('/books/{book}', 'BookController@update');
Route::delete('/books/{book}', 'BookController@destroy');

Route::get('/authors', 'AuthorController@index');
Route::get('/authors/create', 'AuthorController@create');
Route::post('/authors', 'AuthorController@store');
Route::get('/authors/{author}', 'AuthorController@show');
Route::get('/authors/{author}/edit', 'AuthorController@edit');
Route::put('/authors/{author}', 'AuthorController@update');
Route::delete('/authors/{author}', 'AuthorController@destroy');

// AJAX calls
Route::post('/books/change-borrowed-status', 'AjaxController@changeBorrowedStatus');

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function books() {

        return $this->hasMany(Book::class);
    }
}

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function author() {

        return $this->belongsTo(Author::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AjaxController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;

class ajaxController extends Controller
{

    public function changeBorrowedStatus() {

        if (request()->ajax()) {
            $data = request()->validate([
                'id' => 'required|integer',
                'is_borrowed' => 'boolean',
            ]);

            $book = Book::where(['id' => $data['id']]);
            $book->update(['is_borrowed' => $data['is_borrowed']]);
        }
    }

}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Author;

class AuthorController extends Controller
{
    public function index() {

        $authors = Author::withCount('books')->orderBy('surname', 'ASC')->paginate(20); // withCount is for count column in author list
        
        return view('author.index', compact('authors'));
    }

    public function create() {

        return view('author.create');
    }

    public function store() {

        if ($this->authorExists()) {
            return back()->withInput()->withErrors(['formError' => ['Author already exists!']]);
        }

        Author::create($this->validatedFormData());

        return redirect('/authors');
    }

    public function show(Author $author) {
        
        return view('author.show', [
            'author' => $author,
            'objectType' => 'author',
            'objectName' => $author->name . ' ' . $author->surname,
        ]);
    }

    public function edit(Author $author) {

        return view('author.edit', compact('author'));
    }

    public function update(Author $author) {

        if (! $this->authorExists()) {
            $author->update($this->validatedFormData());
        }

        return redirect('/authors/' . $author->id);
    }

    public function destroy(Author $author) {

        $author->books()->delete();
        $author->delete();

        return redirect('/authors');
    }

    public function validatedFormData() {

        return request()->validate([
            'name' => 'required|min:2|max:255',
            'surname' => 'required|min:3|max:255',
        ]);
    }

    public function authorExists() {

        return Author::where($this->validatedFormData())->exists();
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;
use App\Models\Author;

class BookController extends Controller
{
    
    public function index() {

        $books = Book::orderBy('title', 'ASC')->paginate(20);

        return view('book.index', compact('books'));
    }

    public function create() {

        return view('book.create', ['authors' => Author::get()]);
    }

    public function store() {

        $author = Author::where(['id' => $this->validatedFormData()['author_id']])->first();
        $book = new Book($this->validatedFormData());
        $author->books()->save($book);

        return redirect('/books');
    }

    
    public function show(Book $book) {

        return view('book.show', [
            'book' => $book,
            'objectType' => 'book',
            'objectName' => $book->title,
        ]);
    }

    public function edit(Book $book) {

        return view('book.edit', [
            'authors' => Author::get(),
            'book' => $book,
        ]);
    }

    public function update(Book $book) {

        $book->update($this->validatedFormData());

        return redirect('/books/' . $book->id);
    }

    public function destroy(Book $book) {
        
        $book->delete();

        return redirect('/books');
    }

    public function validatedFormData() {

        $data = request()->validate([
            'title' => 'required|min:2|max:255',
            'author_id' => 'required|integer|gt:0',
            'is_borrowed' => 'boolean',
        ]);

        if (! request()->has('is_borrowed')) {
            $data['is_borrowed'] = 0;
        }

        return $data;
    }

    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>Book Library | @yield('title')</title>
        
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="{{ asset('js/app.js') }}" defer></script>

        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="bg-light">

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                
                    @include('partials.menu')

                    @yield('main')

                </div>
            </div>
        </div>

    </body>
</html>

resources/views/author/create.blade.php
@extends('app')

@section('title', 'Add new author')

@section('main')

    <h1>Add new author</h1>

    <form action="/authors" method="post">
        @csrf

        <div class="form-group">
            <label for="name">Author's name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter author's name" value="{{ old('name') }}">
            @error('name')
                <span class="text-danger">{{ $message }}</span>
            @enderror
        </div>
        <div class="form-group">
            <label for="surname">Author's surname</label>
            <input type="text" class="form-control" id="surname" name="surname" placeholder="Enter author's surname" value="{{ old('surname') }}">
            @error('surname')
                <span class="text-danger">{{ $message }}</span>
            @enderror
        </div>
        
        <p class="text-danger">{{ $errors->first('formError') ?? '' }}</p>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

@endsection

resources/views/author/edit.blade.php
@extends('app')

@section('title', 'Edit author')

@section('main')
    <h1>Edit author</h1>

    <form action="/authors/{{ $author->id }}" method="post">
        @csrf
        @method('put')

        <div class="form-group">
            <label for="name">Author's name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter author's name" value="{{ $author->name }}">
            @error('name')
                <span class="text-danger">{{ $message }}</span>
            @enderror
        </div>
        <div class="form-group">
            <label for="surname">Author's surname</label>
            <input type="text" class="form-control" id="surname" name="surname" placeholder="Enter author's surname" value="{{ $author->surname }}">
            @error('surname')
                <span class="text-danger">{{ $message }}</span>
            @enderror
        </div>
        
        <p class="text-danger">{{ $errors->first('formError') ?? '' }}</p>

        <button type="submit" class="btn btn-primary">Submit changes</button>
    </form>

@endsection

resources/views/author/index.blade.php
@extends('app')

@section('title', 'All authors')

@section('main')
    
    <h1 class="text-center">Authors</h1>

    <div>
        <a class="btn btn-primary" href="/authors/create">Add new author</a>
    </div>
    <br>
    
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Surname</th>
                <th scope="col">Book count</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        @forelse($authors as $author)
            <tr>
                <td>{{ $author->name }}</td> 
                <td>{{ $author->surname }}</td>
                <td>{{ $author->books_count }}</td>
                <td><a href="/authors/{{ $author->id }}">Detail</a></td>
            </tr>
        @empty
            <tr>
                <td colspan=4>No authors available.</td>
            </tr>
        @endforelse
    </table>

    <div class="d-flex justify-content-center">
        {{ $authors->links() }}
    </div>
    
@endsection

resources/views/author/show.blade.php
@extends('app')

@section('title', 'Author detail')

@section('main')
    
    <h1 class="text-center">Author detail</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Surname</th>
                <th scope="col">Book count</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $author->name }}</td> 
                <td>{{ $author->surname }}</td>
                <td>{{ $author->books_count ?? 0 }}</td>
                <td><a href="/authors/{{ $author->id }}/edit">Edit</a></td>
                <td>
                    <form class="delete-form" action="/authors/{{ $author->id }}" method="post">
                        @csrf
                        @method('delete')
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </form>
                </td>
            </tr>
        </tbody>
    </table>

    @include('partials.modal')
    
@endsection

resources/views/book/create.blade.php
@extends('app')

@section('title', 'Add new book')

@section('main')
    <h1>Add new book</h1>

    <form action="/books" method="post">
        @csrf

        <div class="form-group">
            <label for="author_id">Book author</label>
            <select class="form-control" id="author_id" name="author_id">
                <option>Choose</option>
                @forelse($authors as $author)
                    <option value="{{ $author->id }}">{{ $author->name }} {{ $author->surname }}</option>
                @empty
                    <option>No authors available</option>
                @endforelse
            </select>
            @error('author_id')
                <span class="text-danger">{{ $message }}</span>
            @enderror
        </div>

        <div class="form-group">
            <label for="title">Book title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Enter book title">
            @error('title')
                <span class="text-danger">{{ $message }}</span>
            @enderror
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

@endsection

resources/views/book/edit.blade.php
@extends('app')

@section('title', 'Edit book')

@section('main')
    <h1>Edit book</h1>

    <form action="/books/{{ $book->id }}" method="post">
        @csrf
        @method('put')

        <div class="form-group">
            <label for="author_id">Book author</label>
            <select class="form-control" id="author_id" name="author_id">
                <option>Choose</option>
                @forelse($authors as $author)
                    <option value="{{ $author->id }}" @if($book->author_id === $author->id)selected="selected"@endif>{{ $author->name }} {{ $author->surname }}</option>
                @empty
                    <option>No authors available</option>
                @endforelse
            </select>
            @error('author_id')
                <span class="text-danger">{{ $message }}</span>
            @enderror
        </div>

        <div class="form-group">
            <label for="title">Book title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Enter book title" value="{{ $book->title }}">
            @error('title')
                <span class="text-danger">{{ $message }}</span>
            @enderror
        </div>
        
        <div class="form-group">
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="is_borrowed" name="is_borrowed" value="1" @if($book->is_borrowed)checked="checked"@endif>
                <label class="form-check-label" for="is_borrowed">Borrowed</label>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit changes</button>
    </form>

@endsection

resources/views/book/index.blade.php
@extends('app')

@section('title', 'All books')

@section('main')
    
    <h1 class="text-center">Books</h1>

    <div>
        <a class="btn btn-primary" href="/books/create">Add new book</a>
    </div>
    <br>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Borrowed</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @forelse($books as $book)
                <tr>
                    <td>{{ $book->title }}</td> 
                    <td>{{ $book->author->name }} {{ $book->author->surname }}</td>
                    <td>
                        <input type="checkbox" name="is_borrowed" class="is_borrowed" value="1" data-book-id="{{ $book->id }}" @if($book->is_borrowed)checked="checked"@endif>
                    </td>
                    <td><a href="/books/{{ $book->id }}">Detail</a></td>
                </tr>
            @empty
                <tr>
                    <td colspan=4>No books available.</td>
                </tr>
            @endforelse
        <tbody>
    </table>

    <div class="d-flex justify-content-center">
        {{ $books->links() }}
    </div>
    
@endsection

resources/views/book/show.blade.php
@extends('app')

@section('title', 'Book detail')

@section('main')
    
    <h1 class="text-center">Book detail</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Borrowed</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $book->title }}</td> 
                <td>{{ $book->author->name }} {{ $book->author->surname }}</td>
                <td>
                    <input type="checkbox" name="is_borrowed" class="is_borrowed" value="1" data-book-id="{{ $book->id }}" @if($book->is_borrowed)checked="checked"@endif>
                </td>
                <td><a href="/books/{{ $book->id }}/edit">Edit</a></td>
                <td>
                    <form class="delete-form" action="/books/{{ $book->id }}" method="post">
                        @csrf
                        @method('delete')
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </form>
                </td>
            </tr>
        </tbody>
    </table>

    @include('partials.modal')

@endsection

resources/views/partials/menu.blade.php
<div class="navbar">
    <ul class="list-inline main-menu">
        <li class="list-inline-item"><a href="/books">Books</a></li>
        <li class="list-inline-item"><a href="/authors">Authors</a></li>
    </ul>
</div>

resources/views/partials/modal.blade.php
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete {{ $objectType ?? '' }}?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Do you really wish to delete {{ $objectType ?? '' }} "{{ $objectName ?? '' }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-primary" id="confirmYes">Yes</button>
      </div>
    </div>
  </div>
</div>